import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Image from 'next/image';
import { useState } from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Arsh Ballagan</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className='bg-white px-10 md:px-20 lg:px-40'>
          <section className="mb-20">
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl font-mono'>Arsh Ballagan</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' />
                </li>
                <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-500 font-medium md:text-6l'>Arsh Ballagan</h2>
              <h3 className='text-2xl py-2 md:text-3xl'>Developer and entrepreneur</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>
                A collection of my past and current projects, as well
                as some of my thoughts and passions.
              </p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <a href="https://www.linkedin.com/in/arshballagan/" target="_blank" rel="noreferrer">
                <AiFillLinkedin className='cursor-pointer' />
              </a>
              <a href="https://twitter.com/0xArshdeep" target="_blank" rel="noreferrer">
                <AiFillTwitterCircle className='cursor-pointer' />
              </a>
              <a href="https://github.com/0xArshdeep" target="_blank" rel="noreferrer">
                <AiFillGithub className='cursor-pointer' />
              </a>
            </div>
          </section>

          <section className='py-10'>
            <div>
              <h3 className='text-3xl py-1'>A Little About Me...</h3>
              <p className='text-md py-2 leading-8 text-gray-800'>
                Lorem ipsum Lorem <span className='text-teal-500'>ipsum</span> Lorem ipsum Lorem ipsum Lorem ipsum
                Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum
              </p>
              <p className='text-md py-2 leading-8 text-gray-800'>
                Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
                Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum
              </p>
            </div>
          </section>
          <section className='py-10'>
            <div>
            <h3 className='text-3xl py-1'>Currently Building:</h3>
            </div>
            <div className='lg:flex gap-10'>
              <div>
                <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                  
                  <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                  <p className='py-2'>
                    Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
                    Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum
                  </p>
                  <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                  <p className='text-gray-800 py-1'>Photoshop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
                </div>
              </div>
            </div>
          </section>

          <section className='py-10'>
            <div>
              <h3 className='text-3xl py-1'>Blogs</h3>
              <p className='text-md py-2 leading-8 text-gray-800'>
                Lorem ipsum Lorem <span className='text-teal-500'>ipsum</span> Lorem ipsum Lorem ipsum Lorem ipsum
                Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum
              </p>
              <p className='text-md py-2 leading-8 text-gray-800'>
                Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
                Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum
              </p>
            </div>
          </section>
        </main>
      </div>
    </>
  )
}
